### ISSUE TITLE
升级到antd5 ，modal的主色好像不会变

### ISSUE THREAD

**Issue by pangxzi** [bowencool/create-antd-modal#1]
CreateModal
![image](https://user-images.githubusercontent.com/52907799/206340330-8e9adfc5-b61f-41fe-a108-0b133ec85fca.png)

defaultModal
![image](https://user-images.githubusercontent.com/52907799/206340386-cf7516f2-4255-4ddc-8263-30d623c1649b.png)

**Comment by bowencool** [comment]
发布的时候 antd 还没发布 v5 ... 这两天看一下

**Comment by pangxzi** [comment]
> 发布的时候 antd 还没发布 v5 ... 这两天看一下

👌

**Comment by bowencool** [comment]
这个是因为 modal 是动态创建的，不在页面的组件树上，所以获取不到各种 context 的值。
官方利用 useModal 返回 holder 是一种很好的解决办法，就是不够简洁。我尽量想想成本更低的方法

**Comment by pangxzi** [comment]
> 这个是因为 modal 是动态创建的，不在页面的组件树上，所以获取不到各种 context 的值。 官方利用 useModal 返回 holder 是一种很好的解决办法，就是不够简洁。我尽量想想成本更低的方法

好

**Comment by bowencool** [comment]
抱歉这么晚解决，现在你可以使用 `createFunctionWithDefaultProps ` 了，详情查看[文档](https://bowencool.github.io/create-antd-modal/documents/functions/create-modal#createmodal-default-props)

**Comment by bowencool** [comment]
v1.5.0 增加了 useModalCreation，使用更便捷

``` tsx
import React from 'react';
import { Button } from 'antd';
import { useModalCreation } from 'create-antd-modal';
import RootContainer from './RootContainer';

const Demo: React.FC = () => {
  const [contextHolder, createModal] = useModalCreation();
  return (
    <RootContainer>
      <Button
        onClick={() => {
          createModal({
            title: 'Some title',
            content: 'You can see that the i18n and theme configuration works now',
          });
        }}
      >
        Context Providing
      </Button>
      {contextHolder}
    </RootContainer>
  );
};

export default Demo;
```
